influxdb:
  server:
    - name: local
      ip: 172.30.232.250
      port: 8086
      
all:
  measurement: snmptraps
  tags:
    host_dns: host_name
    host_ip: host_ip
    
# Special processing based on Event
mappings:
  UpTimeInstance:
    measurement: link
    tags:
      - UpTimeInstance
    fields:
      - UpTimeInstance
  ClientSessionTrap:
    measurement: link
    tags:
      - ApIfSlotId
      - ApName
      - ClientUsername
      - ClientByIpAddress
      - ApMacAddress
    fields:
      - UpTimeInstance
      - ApIfSlotId
      - ApName
  
