---
# logging
logging: debug

  # Influx DB configuration
influxdb:
  server:
    - name: syslog
      ip: 172.30.232.250
      port: 8086
      db: snmptrapd
      user: sabaszx 
      pass: admin

# All traps processing configuration

all:
  measurement: snmptraps
  tags:
    event: event_name
    apname: ap_name

# Special processing based on strange event
mappings:
  IF-MIB::linkUp:
    measurement: link
    tags:
      - snmpTrapOID
      - ifIndex
      - ifName
    fields:
      - ifAdminStatus
      - ifOperStatus
  IF-MIB::linkDown:
    measurement: link
    tags:
      - snmpTrapOID
      - ifIndex
      - ifName
    fields:
      - ifAdminStatus
      - ifOperStatus
